version: "3.4"

services:
  squid:
    image: "eduinlight-squid"
    container_name: "eduinlight-squid"
    restart: always
    build:
      context: .
    volumes:
      - ./conf:/etc/squid
    ports:
      - 3128:3128
