version: '3.7'

services:
  mongo:
    container_name: tests-mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    networks:
      - mongo
    volumes:
      - ~/.mongodb-data/tests-mongo:/data/db
    extends:
      file: ../healthcheks.yaml
      service: mongo

  mongo-express:
    container_name: tests-mongo-express
    image: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    ports:
      - "4000:8081"
    networks:
      - mongo

networks:
  mongo:
    name: tests-mongo
