version: "3.7"

services:
  api:
    image: "debian:latest"
    container_name: "debian"
    user: 'root:root'
    stdin_open: true
    tty: true
    command: bash
    volumes:
      - .:/home
    networks:
      - debian 

networks:
  debian:
    name: "debian"
